import os
import re
import yaml
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional
import sys

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.append(str(PROJECT_ROOT))

from src.config import settings

RESEARCH_DIR = PROJECT_ROOT / "thoughts" / "shared" / "research"
OUTPUT_FILE = RESEARCH_DIR / "README.md"

def parse_frontmatter(file_path: Path) -> Dict:
    """
    Parse YAML frontmatter from a markdown file.
    """
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Regex to extract frontmatter between ---
    match = re.match(r'^---\s*\n(.*?)\n---\s*\n', content, re.DOTALL)
    if not match:
        return {}

    try:
        frontmatter = yaml.safe_load(match.group(1))
        return frontmatter if isinstance(frontmatter, dict) else {}
    except yaml.YAMLError:
        return {}

def format_date(date_obj) -> str:
    """Format date for display."""
    if isinstance(date_obj, datetime):
        return date_obj.strftime("%Y-%m-%d")
    elif isinstance(date_obj, str):
        # Try to parse string date
        try:
            # Handle standard ISO format
            dt = datetime.fromisoformat(date_obj.replace('Z', '+00:00'))
            return dt.strftime("%Y-%m-%d")
        except ValueError:
            return date_obj
    return str(date_obj)

def generate_index():
    """
    Scan research directory and generate README.md index.
    """
    print(f"Scanning research documents in: {RESEARCH_DIR}")
    
    if not RESEARCH_DIR.exists():
        print(f"Research directory not found: {RESEARCH_DIR}")
        return

    documents = []
    
    for file_path in RESEARCH_DIR.glob("*.md"):
        if file_path.name == "README.md":
            continue
            
        frontmatter = parse_frontmatter(file_path)
        
        # Use filename date as fallback if not in frontmatter
        # convention: YYYY-MM-DD_HH-MM-SS_topic.md
        filename_date = "Unknown"
        match = re.match(r'(\d{4}-\d{2}-\d{2})', file_path.name)
        if match:
            filename_date = match.group(1)
            
        doc_info = {
            "file_name": file_path.name,
            "path": file_path,
            "date": frontmatter.get("date", filename_date),
            "topic": frontmatter.get("topic", file_path.stem),
            "status": frontmatter.get("status", "unknown"),
            "tags": frontmatter.get("tags", []),
            "author": frontmatter.get("researcher", frontmatter.get("author", "unknown"))
        }
        documents.append(doc_info)

    # Sort documents by date (newest first)
    documents.sort(key=lambda x: str(x["date"]), reverse=True)
    
    # Generate Markdown content
    content = [
        "# Research Index",
        "",
        "Auto-generated index of research documents and architectural decisions.",
        "",
        f"_Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_",
        "",
        f"**Total documents: {len(documents)}**",
        "",
        "| Date | Topic | Status | Tags | Author |",
        "|------|-------|--------|------|--------|",
    ]

    for doc in documents:
        date_str = format_date(doc["date"])
        topic = doc["topic"]
        status = doc["status"]
        tags = ", ".join(doc["tags"]) if doc["tags"] else "-"
        author = doc["author"]
        file_link = f"[{doc['file_name']}]({doc['file_name']})"

        content.append(f"| {date_str} | {file_link} | {status} | {tags} | {author} |")

    content.append("")
    content.append("---")
    content.append("")
    content.append("*Generated by `scripts/utils/generate_research_index.py`*")

    # Write output
    output_content = "\n".join(content)

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(output_content)

    print(f"Generated index with {len(documents)} documents")
    print(f"Output written to: {OUTPUT_FILE}")


if __name__ == "__main__":
    generate_index()